version: "2"
services:
  apache:
    image: eeacms/apache:2.4-1.0
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - varnish
    environment:
      SERVER_ADMIN: "helpdesk@wise-test.eionet.europa.eu"
      SERVER_NAME: "wise-test.eionet.europa.eu"
      RewriteRule: "^/(.*) http://varnish/VirtualHostBase/http/wise-test.eionet.europa.eu:80/Plone/VirtualHostRoot/$$1 [P,L]"
      TZ: "Europe/Copenhagen"
  varnish:
    image: eeacms/varnish-emrt-necd:1.5
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - haproxy
    environment:
      VARNISH_BACKEND_HOST: "haproxy"
      VARNISH_BACKEND_PORT: "5000"
      VARNISH_MEMORY: "2G"
      TZ: "Europe/Copenhagen"
  haproxy:
    image: eeacms/haproxy:1.7-1.0
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - plone
    environment:
      BACKENDS: "plone"
      BACKENDS_PORT: "8080"
      DNS_ENABLED: "True"
      TZ: "Europe/Copenhagen"
  plone:
    image: eeacms/plone-wise:v0.5
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - zeoserver
    - memcached
    environment:
      ZOPE_MODE: "zeo_client"
      TZ: "Europe/Copenhagen"
    volumes:
    - wise-downloads:/data/downloads
    - wise-plone-data:/data
  async:
    image: eeacms/plone-wise:latest
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - zeoserver
    - memcached
    environment:
     ZOPE_MODE: "zeo_async"
     TZ: "Europe/Copenhagen"
    volumes:
    - wise-downloads:/data/downloads
    - wise-async-data:/data
  memcached:
    image: memcached:1.4.35
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - "-m"
    - "2048"
  zeoserver:
    image: plone:4.3.10
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=staging1-ams-02
    environment:
      TZ: "Europe/Copenhagen"
    command:
    - zeoserver
    volumes:
    - wise-data:/data
  rsync-server:
    image: eeacms/rsync
    labels:
      io.rancher.scheduler.affinity:host_label: hostname=staging1-ams-02
    command:
    - server
    ports:
    - "22"
    volumes:
    - wise-data:/data
    environment:
      SSH_AUTH_KEY_1: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtpQ268Pd9FQhEl8NxsCVVRc2kM42883/AEFqeZ+gh2mEMXRdykK1VgXgcuPhHTnhFjWHXk7cgVWkmFQ2jqdVSbAl2aLFYRDNCqkqQM/Itg93HTWTrL89cv3hzWTpzWxNqVE2eHyDysPul41F8lw/+q9hF4xLijFCe2vbVhaHTB8GydQwjtPyv0u28adLnN/02GGhwF2Rh4a6p+v4ANLniw8XNW7fU5HtyZeZkzpdr2k+UJi+A8r8XnKvP4v4ltb/dRIuRI3Rupz1XW5gkjGo92w9+thzxF8DKf3BtFuHIOIA2wCXzGZ5jxzeKZNppitBGgII7VcaKYWJxqCuDuQ4jQ== tibi@localhost"

volumes:
  wise-plone-data:
    per_container: true
  wise-async-data:
    per_container: true
  wise-data:
    driver: rancher-nfs
  wise-downloads:
    driver: rancher-nfs
