version: '2'
services:
  apache:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 80
      interval: 30000
      initializing_timeout: 90000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000
  haproxy:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 4242
      interval: 30000
      initializing_timeout: 90000
      unhealthy_threshold: 3
      strategy: recreate
      healthy_threshold: 2
      response_timeout: 3000
  memcached:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 11211
      interval: 30000
      initializing_timeout: 90000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 3000
      healthy_threshold: 2
  plone:
    scale: 2
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 30000
      initializing_timeout: 90000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      response_timeout: 6000
      healthy_threshold: 2
  async:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8080
      interval: 30000
      initializing_timeout: 90000
      unhealthy_threshold: 3
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      response_timeout: 6000
      healthy_threshold: 2
  zeoserver:
    scale: 1
    upgrade_strategy:
      start_first: true
    health_check:
      port: 8100
      interval: 30000
      initializing_timeout: 90000
      unhealthy_threshold: 3
      strategy: recreate
      response_timeout: 6000
      healthy_threshold: 2
