version: "2"
services:
  code:
    image: eeacms/plone-wise:devel
    entrypoint:
    - "buildout"
    command:
    - "-c"
    - "source.cfg"
    volumes:
    - ./src/source.cfg:/plone/instance/source.cfg:ro
    - ./src:/plone/instance/src:z
